#define STATUS_MALLOC_FAIL -1
#define STATUS_INVALID_PARAMETER_1 -2
#define STATUS_INVALID_PARAMETER_2 -3
#define STATUS_INVALID_PARAMETER_3 -4
#define STATUS_INDEX_OUT_OF_BOUNDS -5
#define STATUS_NOT_INITIALIZED -10

